model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val/loss
  mode: min
  save_top_k: 1
  save_last: true
  dirpath: ${outputs_dir}/checkpoints
  filename: "epoch{epoch:02d}-valloss{val/loss:.2f}"

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: val/loss
  patience: 50
  mode: min

prediction_scatter:
  _target_: src.callbacks.prediction_plot_callback.PredictionPlotCallback
  output_dir: ${outputs_dir}

loss_curves:
  _target_: src.callbacks.loss_curves.LossCurvesCallback
  output_dir: ${outputs_dir}

epoch_time_logger:
  _target_: src.callbacks.epoch_time_logger.EpochTimeLogger

diagnostic_plot:
  _target_: src.callbacks.diagnostic_plot.DiagnosticSpectraCallback
  num_samples: 5
  output_dir: ${outputs_dir}
  # Pass all the required noise parameters
  use_cauchy_noise: ${data.use_cauchy_noise}
  cauchy_mu: ${data.cauchy_mu}
  cauchy_sigma: ${data.cauchy_sigma}
  cauchy_threshold: ${data.cauchy_threshold}


corner_plots:
      _target_: src.callbacks.hybrid_corner_plot_callback.HybridCornerPlotCallback
      param_names: ${data.model_params}
      log_scale_params: ${data.log_scale_params}
      output_dir: ${outputs_dir}/corner_plots
      plot_every_n_epochs: 5         # Plot every 5 epochs
      num_samples_to_plot: 10      # Plot the first 10 validation samples
      num_posterior_samples: 5000  # Number of points for the plot's histograms/scatter
      plot_in_log_space: true

#debug:
#  _target_: src.callbacks.debug.DataloaderDebugCallback

#covariance_heatmap:
#  _target_: src.callbacks.covariance_heatmap.CovarianceHeatmapCallback
#  param_names: ${data.model_params}
#  output_dir: ${outputs_dir}

# MixtureMDNVizCallback:
#   _target_: src.callbacks.mixture_mdn_viz.MixtureMDNVizCallback
#   param_pairs: [ ["D","L"], ["rr","ro"] ]
#   max_ellipse_samples: 60
#   output_dir: ${outputs_dir}
#   job_id: ${job_id}


#should go last to be sure to clear cache after all other callbacks
# CacheReset:
#   _target_: src.callbacks.prediction_plot_callback.CacheResetCallback